name: build .exe

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install --no-cache-dir --prefer-binary -r requirements.txt
      - run: ui/make.bat
      - uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: coj_maps_downloader.py
          msvc: latest
          mode: standalone
          output-file: coj_maps_downloader.exe
          windows-console-mode: disable
          enable-plugins: pyside6
      - run: cp LICENSE build/coj_maps_downloader.dist/
      - uses: thedoctor0/zip-release@0.7.6
        with:
          filename: coj-maps-downloader.zip
          directory: build/coj_maps_downloader.dist/
          type: 7z
      - run: dir -s
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/coj_maps_downloader.dist/coj-maps-downloader.zip
