name: build release (win + linux)

on:
  push:
    tags: [ '*.*.*' ]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: build ${{ matrix.platform }} (${{ matrix.nuitka_mode }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            nuitka_mode: standalone
            nuitka_output: coj_maps_downloader.exe
          - os: windows-latest
            platform: windows
            nuitka_mode: onefile
            nuitka_output: coj_maps_downloader.exe
          - os: ubuntu-latest
            platform: linux
            nuitka_mode: standalone
            nuitka_output: coj_maps_downloader

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install deps
        run: pip install --no-cache-dir --prefer-binary -r requirements.txt
      - name: Build UI (Windows)
        if: runner.os == 'Windows'
        run: ui/make.bat
      - name: Build UI (Linux)
        if: runner.os == 'Linux'
        working-directory: ui
        run: make
      - name: Nuitka Build
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: coj_maps_downloader.py
          msvc: latest
          mode: ${{ matrix.nuitka_mode }}
          output-file: ${{ matrix.nuitka_output }}
      - name: Add LICENSE (standalone)
        if: matrix.nuitka_mode == 'standalone'
        shell: bash
        run: cp LICENSE build/coj_maps_downloader.dist/
      - name: Create archive (standalone)
        if: matrix.nuitka_mode == 'standalone'
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}.zip
          directory: build/coj_maps_downloader.dist/
          type: 7z
      - name: Rename onefile
        if: matrix.nuitka_mode == 'onefile'
        shell: bash
        run: mv build/${{ matrix.nuitka_output }} coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}.exe
      - name: Upload workflow artifact (standalone)
        if: matrix.nuitka_mode == 'standalone'
        uses: actions/upload-artifact@v6
        with:
          name: coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.nuitka_mode }}
          path: build/coj_maps_downloader.dist/coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}.zip
      - name: Upload workflow artifact (onefile)
        if: matrix.nuitka_mode == 'onefile'
        uses: actions/upload-artifact@v6
        with:
          name: coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.nuitka_mode }}
          path: coj-maps-downloader-${{ env.VERSION }}-${{ matrix.platform }}.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - name: Create/Update GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          artifacts: dist/*
          generateReleaseNotes: true
